### ISSUE TITLE
[BUG] Cannot set custom item after selecting one from dropdown list

### ISSUE THREAD

**Issue by arnWolff** [janosh/svelte-multiselect#89] opened 2022-07-01 07:19 UTC
Hello and thank you for this great svelte component.

There is a bug when `allowUserOptions` is used.
If you select an already existing item from the dropdown list using your mouse or the arrows and then use keyboard to type some text (custom item) on the autofocused input (meaning without user reclicking inside the input), the custom item with the previously chosed item, both disappear.
Still then typing some more text in the input would make the previously item of the dropdown list to reappear inside the input, and so on...

If using the mouse to click the input after adding item from dropdown list, the MultiSelect works as expected.

You can reproduce this bug on [official demo example](https://svelte-multiselect.netlify.app/allow-user-options)

Regards.

**Comment by janosh** [comment] 2022-07-01 13:03
Good catch and thanks for reporting. I think I found the cause. Should be fixed in v5.0.3.

**Closed** 2022-07-01 14:19 UTC

**Comment by janosh** [comment] 2022-07-01 14:25
For later reference and to make sure, we were talking about the same bug, this screen recording shows the problem:

https://user-images.githubusercontent.com/30958850/176913391-699bc579-50ef-4ef2-9586-c9831566408a.mp4

**Comment by arnWolff** [comment] 2022-07-01 14:44
That's it!

Thanks you.
