### ISSUE TITLE
Single and multi style

### ISSUE THREAD

**Issue by rysson** [janosh/svelte-multiselect#2] opened 2021-06-19 14:36 UTC
First, it's look great, thank you.

I'm not sure it it's a bug but I have:
- for `single=false` options looks like `ul.tokens > li.token`
- for `single=true` options looks like `ul.tokens`, option name is directly in `ul.tokens`, so it's not styled.

Example, the same settings and options except `single=true` on top.
![20210619-162651-155x128](https://user-images.githubusercontent.com/5898312/122645671-c424cb80-d11b-11eb-8957-079d78fadf0d.png)

Maybe you could add `li.token` and add some info about single (`.multiselect.single` or `ul.tokens.single` or new added `ul.tokens.single`). to help styling multi and single select.

If you won't to add `li` the `single` class will be very useful too.

**Comment by janosh** [comment] 2021-06-19 16:56
Thanks for giving this a try!

The behavior you show in your screenshot is intentional (not a bug) but I haven't thought about it much yet. It could perhaps be improved.

If I understand you correctly, you're suggesting two things?

1. Use the same markup structure for single and multiple select. I.e. wrap even a single selected token in a list item tag?
  Not a fan of that to be honest. Using tags suggests to users that they should be able to select more than one option when they actually can't.
2. Add a class `.single` to the top-level `div.multiselect` based on whether `single` is true or not.
  That sounds like a good idea to me. Happy to add it if that's what you meant?

**Comment by rysson** [comment] 2021-06-19 17:49
Thanks for so quick replay.

1. Single option is already in `ul`, that suggest list. Of course, instead `li` it could be in another tag `span` or `div`. BTW list with one element is also (a little simple) list. Extra idea, what if you implement max-selected or something similar? And set it to one? Of course it is only idea, not must to have.
2. Yes, this is enough to apply styles to this case. I'll be happy if you could add it.

**Comment by janosh** [comment] 2021-06-20 16:54
> Extra idea, what if you implement max-selected or something similar? And set it to one? Of course it is only idea, not must to have.

Having the ability to specify any positive integer number of maximally selectable options is a great idea. I added a new prop `maxSelect` in v1.1.3. `div.multiselect` will now have class `single` if you pass `maxSelect={1}`.

**Comment by rysson** [comment] 2021-06-20 18:47
It's great idea, thanks. I've tested.
- `single` class is present when `maxSelect={1}` – wonderful
- Dialog closes on rich `maxSelect` – nice. It's doesn't work for `maxSelect={1}` or I do something wrong.
- One thing more, I think it will be better to one-click options change when `maxSelect={1}`. Now I can select options than I need to clear selection and select another option. I can not directly click another option and I can not deselect option.
- I'm new in front-end, could you point me how to set initial value? If I set `let channel = 'a';` and use `bind:selected={channel}` nothing is set. When I set `channel` on `setTimeout` it works. The same for multi-select.

**Comment by janosh** [comment] 2021-06-21 06:27
Thanks for putting this component through its paces! Lots of good ideas from your side.

> Dialog closes on rich maxSelect – nice. It's doesn't work for maxSelect={1} or I do something wrong.

No, that was my fault. I noticed a problem in `function add(token) { ... }` just a minute after I published v1.1.3. Had already fixed it locally but not republished yet.

![Screen Shot 2021-06-21 at 08 09 33](https://user-images.githubusercontent.com/30958850/122715699-8f268f00-d269-11eb-9aab-ce159a4f8f1f.png)

> One thing more, I think it will be better to one-click options change when maxSelect={1}. Now I can select options than I need to clear selection and select another option. I can not directly click another option and I can not deselect option.

Makes sense. That should work now.

> I'm new in front-end, could you point me how to set initial value? If I set let channel = 'a'; and use bind:selected={channel} nothing is set. When I set channel on setTimeout it works. The same for multi-select.

That was due to

```js
$: selected = single ? `` : []
```

This should fix it:

```js
if (!selected) selected = single ? `` : []
```

Now you can simply do

```js
<script>
  let channel = 'a';
  const channelList = ['a', 'b', 'c'];
</script>
<MultiSelect bind:selected={channel} options={channelList} maxSelect={1} />
```

All changes published in v1.1.4. Let me know if it's working for you.

**Comment by rysson** [comment] 2021-06-22 19:06
It's perfect now, thanks a lot!

Maybe:
- it's possible to add simple `<span>` around text  single (`maxSelect={1}`), it will be easier to style and should not break nothing.
- switch on (or add flag to enable) to open combobox on click on whole area especially on single text not only on empty space on the right (`input`). BTW now if selected text is very long it looks strange:
![20210622-205512-554x90](https://user-images.githubusercontent.com/5898312/122984206-0c9eec00-d39d-11eb-80a8-dadaab1da94c.png)
- fix backspace behavior. On multi-select I selected *test* and type `12`
![20210622-205331-2560x1440 a](https://user-images.githubusercontent.com/5898312/122984550-6d2e2900-d39d-11eb-81c3-7a3c662dbf39.png)
then I pressed backspace
![20210622-205339-2560x1440 a](https://user-images.githubusercontent.com/5898312/122984620-8040f900-d39d-11eb-8310-a9c0523dc08b.png)
it seems that backspace remove one character from input and remove one tag too.

**Comment by janosh** [comment] 2021-06-23 14:58
> it's possible to add simple <span> around text single (maxSelect={1}), it will be easier to style and should not break nothing.

Done.

> switch on (or add flag to enable) to open combobox on click on whole area especially on single text not only on empty space on the right (input). BTW now if selected text is very long it looks strange:

Didn't add a flag but opening the options on clicking already selected tags is now the default behavior.

> it seems that backspace remove one character from input and remove one tag too.

Oops, my bad. Fixed now.

Didn't look at the weird layout for very long texts yet. Will do as time permits.

Also, since this issue has been dragging on, could you open a new one for future bugs/features? Thanks!

**Closed by janosh** 2021-06-23 14:58 UTC

**Comment by rysson** [comment] 2021-06-23 19:23
Sure, one issue – one issue :-)

Now it's even more awesome, thank you a lot!
